services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: acars
      MYSQL_USER: acars
      MYSQL_PASSWORD: acars_password
    healthcheck:
      test: ["CMD-SHELL", "mysql -uacars -pacars_password -e 'SELECT 1' acars"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  otel:
    build:
      context: ..
      dockerfile: docker/otel.Dockerfile

  tests:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      otel:
        condition: service_started
    volumes:
      - ../htmlcov:/app/htmlcov
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: acars
      MYSQL_PASSWORD: acars_password
      MYSQL_DB: acars

      REDIS_HOST: redis
      REDIS_PORT: 6379

      VATSIM_OAUTH_CLIENT_ID: 0
      VATSIM_OAUTH_CLIENT_SECRET: supersecret
      VATSIM_OAUTH_REDIRECT_URI_AIRCRAFT: https://efps.vnpas.uk/oauth/token/
      VATSIM_OAUTH_REDIRECT_URI_ATSU: https://efps.vnpas.uk/oauth/token/
      OTLPS_ENDPOINT: otel
      OTLPS_PORT: 4317
      OTEL_EXPORTER_OTLP_ENDPOINT: otel
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: otel
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: otel
      JWT_SECRET: KuRgN89vGrBHMaBY8oPxBv4EXkm9WlHaQaWyp6expqchdQpMyf8xhYzuBoCPzhu
      JWT_ALGORITHM: HS256
      PWDLIB_SALT: ilF5QxKce3b9Sb6NpDw465clBeXrrLXkM2gZROvqRGDUIkh7433ymPhbIVKh5aI

      PYTHONPATH: /app
      RUNNING_IN_DOCKER: "true"
