"""added sysconfig

Revision ID: 12aa8f8d252d
Revises: 7514e0e6d9ac
Create Date: 2026-06-20 19:04:10.102107

"""
from pathlib import Path
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '12aa8f8d252d'
down_revision: Union[str, Sequence[str], None] = '7514e0e6d9ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    sql_path = Path(__file__).parent / "sql" / "systemconfig.sql"

    op.execute(sql_path.read_text())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
