"""initial schema

Revision ID: 7514e0e6d9ac
Revises: 
Create Date: 2026-06-20 17:08:17.648968

"""
from pathlib import Path
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7514e0e6d9ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlineapikey',
    sa.Column('network', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('airline_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('airline_callsign', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created', sa.Float(), nullable=False),
    sa.Column('last_used', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_airlineapikey_api_key'), 'airlineapikey', ['api_key'], unique=False)
    op.create_table('apikey',
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('network', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.Column('last_used', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_api_key'), 'apikey', ['api_key'], unique=False)
    op.create_table('atsucallsignowner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created', sa.Float(), nullable=False),
    sa.Column('last_used', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atsucallsignowner_api_key'), 'atsucallsignowner', ['api_key'], unique=False)
    op.create_index(op.f('ix_atsucallsignowner_owner'), 'atsucallsignowner', ['owner'], unique=False)
    op.create_table('cpdlctypes',
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_number', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('message_intent', sa.Text(), nullable=True),
    sa.Column('message_element', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fans_1_a', sa.Boolean(), nullable=False),
    sa.Column('fans_1_a_atn_b1', sa.Boolean(), nullable=False),
    sa.Column('atn_b1', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('reference_number')
    )
    op.create_index(op.f('ix_cpdlctypes_reference_number'), 'cpdlctypes', ['reference_number'], unique=False)
    op.create_table('systemconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atsucallsign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('atsu_callsign', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.Column('last_used', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['atsucallsignowner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atsucallsign_atsu_callsign'), 'atsucallsign', ['atsu_callsign'], unique=False)
    op.create_index(op.f('ix_atsucallsign_owner_id'), 'atsucallsign', ['owner_id'], unique=False)
    op.create_table('atsuauthorisedcallsign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('callsign', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('atsu_callsign_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Float(), nullable=False),
    sa.Column('last_used', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['atsu_callsign_id'], ['atsucallsign.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['atsucallsignowner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atsuauthorisedcallsign_atsu_callsign_id'), 'atsuauthorisedcallsign', ['atsu_callsign_id'], unique=False)
    op.create_index(op.f('ix_atsuauthorisedcallsign_callsign'), 'atsuauthorisedcallsign', ['callsign'], unique=False)
    op.create_index(op.f('ix_atsuauthorisedcallsign_owner_id'), 'atsuauthorisedcallsign', ['owner_id'], unique=False)
    # ### end Alembic commands ###
    sql_path = Path(__file__).parent / "sql" / "cpdlctypes.sql"

    op.execute(sql_path.read_text())

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atsuauthorisedcallsign_owner_id'), table_name='atsuauthorisedcallsign')
    op.drop_index(op.f('ix_atsuauthorisedcallsign_callsign'), table_name='atsuauthorisedcallsign')
    op.drop_index(op.f('ix_atsuauthorisedcallsign_atsu_callsign_id'), table_name='atsuauthorisedcallsign')
    op.drop_table('atsuauthorisedcallsign')
    op.drop_index(op.f('ix_atsucallsign_owner_id'), table_name='atsucallsign')
    op.drop_index(op.f('ix_atsucallsign_atsu_callsign'), table_name='atsucallsign')
    op.drop_table('atsucallsign')
    op.drop_table('systemconfig')
    op.drop_index(op.f('ix_cpdlctypes_reference_number'), table_name='cpdlctypes')
    op.drop_table('cpdlctypes')
    op.drop_index(op.f('ix_atsucallsignowner_owner'), table_name='atsucallsignowner')
    op.drop_index(op.f('ix_atsucallsignowner_api_key'), table_name='atsucallsignowner')
    op.drop_table('atsucallsignowner')
    op.drop_index(op.f('ix_apikey_api_key'), table_name='apikey')
    op.drop_table('apikey')
    op.drop_index(op.f('ix_airlineapikey_api_key'), table_name='airlineapikey')
    op.drop_table('airlineapikey')
    # ### end Alembic commands ###
